import 'package:meals_app/models/category.dart';
import 'package:meals_app/models/meal.dart';

const List<Category> DUMMY_CATEGORIES = [
  Category(
    id: 'c1',
    name: 'Xào',
    image: 'assets/images/categories/xao.png',
  ),
  Category(
    id: 'c2',
    name: 'Kho',
    image: 'assets/images/categories/kho.png',
  ),
  Category(
    id: 'c3',
    name: 'Nấu',
    image: 'assets/images/categories/nau.png',
  ),
  Category(
    id: 'c4',
    name: 'Nướng',
    image: 'assets/images/categories/nuong.png',
  ),
  Category(
    id: 'c5',
    name: 'Canh',
    image: 'assets/images/categories/canh.png',
  ),
  Category(
    id: 'c6',
    name: 'Hầm',
    image: 'assets/images/categories/ham.png',
  ),
];

const List<Meal> DUMMY_MEALS = [
  Meal(
    id: 'm1',
    name: 'Ếch xào dứa',
    image: 'assets/images/meals/ech_xao_dua.png',
    categories: [
      'c1',
    ],
    ingredients: [
      '1 cân ếch đồng',
      '1 quả dứa, hành tím, tỏi, sả, nghệ tươi, cà chua, hành lá',
      'Các gia vị: bột cari, nước mắm, đường',
    ],
    steps: [
      'Khi mua ếch các bạn hãy lấy tro bếp hoặc lá tre sát vào thân ếch để có thể loại bỏ được chất nhờn của ếch và khi làm thịt ếch sẽ dễ hơn, sau đó bạn hãy lột hết lớp da bên ngoài của ếch rồi mổ lấy phần ruột ở bụng ra nếu bạn muốn tiết kiệm thời gian thì bạn hãy nhờ người bán mổ ếch cho chỉ lấy phần thân và đùi ếch, sau đó về nhà các bạn hãy rửa thật sạch. Để có thể giảm mùi tanh của ếch thì các bạn hãy rửa ếch cùng với nước muối và cho gừng vào bóp sạch, nếu không các bạn có thể cho rượu trắng vào để rửa ếch.',
      'Khi đã làm sạch ếch thì các bạn hãy chặt thịt ếch thành những miếng vừa ăn, dứa gọt sạch vỏ, bỏ mắt rửa sạch rồi thái thành những miếng mỏng vừa. Hành tím, tỏi bóc vỏ, nghệ tươi gọt vỏ sau đó băm nhỏ tất cả. Cà chua rửa sạch thái múi cau hoặc các bạn có thể thái thành những lát mỏng. Hành lá rửa sạch thái khúc, sả bóc hết lớp vỏ già bên ngoài rửa sạch rồi thái nhỏ.',
      'Sau đó các bạn hãy cho nghệ, sả, 3/4 số hành tỏi đã băm nhỏ vào cùng với thịt ếch và cho thêm bột cari, đường, nước mắm đảo thật đều và để ướp khoảng 30 phút.',
      'Khi đã ướp thịt ếch xong các bạn hãy lấy 1 cái chảo rồi cho dầu vào đun nóng và cho hành tỏi vào phi thơm sau đó cho thịt ếch đã ướp gia vị vào xào khoảng 10 phút thì bạn hãy cho dứa đã thái vào chảo xào cùng. Bạn hãy dùng đũa đảo thật đều sau đó cho cà chua đã thái vào chảo xào cùng, bạn hãy xào cho cà chua chín và nêm lại các gia vị sao cho vừa ăn rồi cho hành lá đã thái khúc vào đảo đều rồi tắt bếp. Như vậy là các bạn đã chế biến xong món ếch xào dứa thơm ngon vô cùng hấp dẫn. Các bạn chỉ cần cho ếch xào dứa ra đĩa rồi thưởng thức lúc món ăn vẫn đang còn nóng.'
    ],
    duration: 35,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm2',
    name: 'Ốc xào khế',
    image: 'assets/images/meals/oc_xao_khe.png',
    categories: [
      'c1',
    ],
    ingredients: [
      'Ốc bươu: 300g',
      'Khế xanh: 2-3 quả',
      'Tía tô, lá lốt',
      'Hành khô: 1 củ',
      'Ớt tươi: 1 củ',
      'Gia vị: dầu ăn, bột nêm, mì chính',
    ],
    steps: [
      'Tía tô, lá lốt rửa sạch, thái nhỏ; khế chua rửa sạch, cắt thành hình sao.',
      'Ốc bươu sau khi làm sạch, dùng dao cắt đôi, hành củ bóc vỏ đập dập, băm nhỏ, ớt tươi thái lát.',
      'Đặt chảo lên bếp, phi thơm hành khô với dầu ăn.',
      'Cho khế vào xào qua (nếu bạn không thích ăn chua, có thể cho khế vào một cái bát, thêm một chút xíu muối, bóp bỏ phần nước chua rồi cho vào xào).',
      'Tiếp đến cho ốc bươu vào xào với lửa lớn để thịt ốc săn lại. Nêm gia vị vừa miệng.',
      'Khi ốc xào khế chín thì cho phần tía tô, lá lốt vào đảo nhanh tay, nêm mì chính.',
      'Tắt bếp cho ra đĩa dùng nóng.',
    ],
    duration: 30,
    complexity: Complexity.medium,
    affordability: Affordability.pricey,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    name: 'Thịt băm xào cà tím',
    image: 'assets/images/meals/thit_bam_xao_ca_tim.png',
    categories: [
      'c1',
    ],
    ingredients: [
      '2 quả cà tím',
      '150 g thịt lợn băm nhỏ',
      '1 thìa cà phê muối',
      '2 tép tỏi và gừng băm nhỏ',
      '3 muỗng canh dầu ăn',
      '1 muỗng canh nước tương',
      'Hành lá',
      'Gia vị gồm đường, bột canh, dầu mè, tiêu.',
    ],
    steps: [
      'Rửa sạch và cắt cà tím thành từng khúc nhỏ đều nhau. Ngâm vào nước muối loãng trong 10 phút. Sau đó vớt ra, để ráo nước. Cùng lúc ướp thịt lợn băm với gừng và một ít muối.',
      'Đun nóng 2 thìa canh dầu ăn trong chảo và xào cà tím khoảng 6-9 phút cho đến khi cà chín cháy cạnh thì lấy ra.',
      'Tiếp tục xào chín thịt lợn băm rồi lấy ra khỏi chảo.',
      'Cho gừng, tỏi, hành lá vào đảo qua cho dậy mùi, sau đó cho lại phần cà tím và thịt lợn băm vào. Thêm xì dầu, đường, tiêu và dầu mè vào trộn đều là món ăn đã hoàn thành.',
    ],
    duration: 25,
    complexity: Complexity.medium,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm4',
    name: 'Sườn kho tàu',
    image: 'assets/images/meals/suon_kho_tau.png',
    categories: [
      'c2',
    ],
    ingredients: [
      ' 500 gr sườn non',
      '3 nhánh hành lá thái khúc dài',
      '5 tép tỏi',
      '1 muỗng canh rượu',
      '3 muỗng canh nước tương = xì dầu',
      '1 muỗng canh đường',
      '1/2 muỗng cà phê tiêu đen',
      '1 muỗng canh nước mắm',
      '1 trái ớt sừng',
      '700 ml nước xương gà hay nước lạnh.',
    ],
    steps: [
      'Đầu tiên khi sườn non mua về các bạn lấy sườn chặt miếng vừa ăn, sau đó rửa sườn qua nước có pha muối rồi xả nước lạnh thật sạch.',
      'Sau đó các bạn bắt chảo lên bếp, cho vào 2 muỗng canh dầu, chờ dầu hơi nóng cho hành lá vào xào 1 phút, kế đến cho tỏi vào xào thêm 1 phút nữa.',
      'Tiếp theo cho sườn vào vào cho thật săn rồi mới cho nước tương vào xào 4 phút phút nữa.',
      'Cuối cùng cho nước + rượu và tất cả các gia vị còn lại vào, đậy nắp hầm với lửa vừa. Khi nước hơi sánh lại thì nêm nếm lại cho vừa ăn là tắt bếp.',
      'Thành phẩm và trình bày: Cho sườn kho tàu ra dĩa, trái ớt để lên hay một chút lá mùi ta (ngò) và rác chút hạt tiêu lên trên cho hấp dẫn và dậy vị nhé.',
    ],
    duration: 40,
    complexity: Complexity.hard,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: 'm5',
    name: 'Ốc nấu chuối đậu',
    image: 'assets/images/meals/oc_nau_chuoi_dau.png',
    categories: [
      'c3',
    ],
    ingredients: [
      'Ốc nhồi hoặc ốc vặn: 1kg',
      'Thịt ba chỉ: 200gr',
      'Đậu phụ: 3 bìa',
      'Chuối tiêu xanh: 8 quả',
      'Mẻ: 1/2 bát con ăn cơm',
      'Bì lợn: 100gr',
      'Rau thơm: hành lá, tía tô, lá lốt',
      'Nếu ăn mắm tôm: 1/2 thìa cà phê',
      'Hành, tỏi: mỗi thứ một củ',
      'Nghệ tươi: 1 củ',
    ],
    steps: [
      'Ốc mua về rửa sạch, ngâm nước vo gạo thả vào vài lát ớt để ốc nhả chất bẩn. Rửa sạch lại ốc, chặt phần đuôi ốc, đem luộc qua nước sôi, khêu lấy phần thịt ốc, bỏ phần phân ốc.',
      'Thịt ba chỉ thái con chì hoặc thái miếng vừa ăn đem đảo cho vàng ruộm.',
      'Chuối xanh đem tước vỏ, ngâm nước muối, bổ đôi thái miếng vát chéo, đem luộc qua với một thìa mẻ nghệ để làm giảm độ thâm của chuối. Sau đó cho dầu ăn vào chảo chiên sơ qua chuối cho săn lại khi nấu chín mềm mà không bị nát.',
      'Đậu phụ thái miếng nhỏ rán vàng đều hai mặt, không nên rán non khi nấu sẽ bị nát.',
      'Làm ba loại nước sốt:',
      'Sốt mẻ nghệ: Đem xay nghệ tươi với mẻ, mẻ sẽ làm giảm đi mùi hăng của nghệ.',
      'Sốt bì lợn: Luộc chín mềm, thêm chút nước xay thật mịn, đem lọc lại qua rây. Sốt bì sẽ làm cho nồi chuối đậu thêm béo ngậy, tạo độ sánh.',
      'Sốt chuối: Luộc 4 quả chuối với chút mẻ nghệ để làm giảm độ thâm của chuối cho chín mềm. Bóc phần vỏ đã tước, lấy phần thịt chuối bên trong xay mịn làm sốt.',
      'Vậy là có ba bát nước sốt: chuối xay nhuyễn, bì lợn xay mịn, mẻ nghệ là bí quyết làm món ốc nấu chuối đậu thêm ngon hơn.',
      'Phi thơm hành tỏi băm nhỏ ,cho ốc vào đảo qua, tiếp đến là thịt ba chỉ, chuối thái miếng chiên sơ qua. Rồi nêm mắm tôm, một thìa canh hạt nêm ,đảo cho ngấm gia vị.',
      'Tiếp đến cho 3 thìa canh mẻ nghệ, sốt chuối xay nhuyễn, sốt bì, cho nước xâm xấp, tạo thành hỗn hợp hơi ngả vàng om đến khi chuối chín mềm và phần nước sền sệt.',
      'Nêm nếm gia vị cho vừa ăn, độ chua của mẻ có thể điều chỉnh theo sở thích, thêm các loại rau thơm thái nhỏ vào bắc ra ăn nóng.',
      'Lưu ý: Tuỳ vào độ chua của mỗi người mà điều chỉnh phần mẻ. Nếu quá trình nấu nước om bị loãng quá thì hoà thêm chút bột năng với nước đổ vào nồi chuối đậu tạo độ sền sệt.',
    ],
    duration: 45,
    complexity: Complexity.hard,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
  ),
  Meal(
    id: 'm6',
    name: 'Bò kho',
    image: 'assets/images/meals/bo_kho.png',
    categories: [
      'c2',
    ],
    ingredients: [
      '400g thịt bò nạm.',
      'Rượu trắng.',
      'Bột bắp.',
      'Cà rốt, hành tây, sả cây, hành tím, tỏi, gừng.',
      'Gói xốt gia vị hoàn chỉnh Baron Bò Kho.',
    ],
    steps: [
      'Cho thịt bò vào trụng sơ với một muỗi canh rượu trắng, 5gr gừng. Sau đó cắt khúc vừa ăn.',
      'Ướp thịt với gói Xốt Gia Vị Hoàn Chỉnh Barona - Bò kho và hành tỏi băm khoảng 20 phút.',
      'Phi thơm hành tỏi băm và sả cây đập dập. Cho thịt vào xào săn lại. Thêm 1.5l nước và hầm nhỏ lửa khoảng 1 giờ 15 phút.',
      'Cho tiếp cà rốt vào hầm trong 40 phút. Cuối cùng cho hành tây vào hầm trong 5 phút.',
      'Cho thêm 50ml nước cùng với 20gr bột bắp vào nấu thêm 2 phút.',
      'Tắt bếp, cho bò kho ra tô. Dùng với bánh mì, hủ tiếu hoặc cơm',
    ],
    duration: 30,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm7',
    name: 'Bò nướng sả cuộn lá lốt',
    image: 'assets/images/meals/bo_nuong_sa_la_lot.png',
    categories: [
      'c4',
    ],
    ingredients: [
      '1 gói Xốt Gia Vị Hoàn Chỉnh Barona - Thịt nướng sả',
      '400g bò phi-lê, 50g mỡ heo, 5 cây sả, 16 cái lá lốt',
      '½ thìa canh hành tím băm, vài cọng hành lá, ½ thìa canh tỏi băm',
      'Rau xà-lách, rau thơm các loại, dưa leo, cà rốt.',
      '1 thìa canh giấm, 1 thìa cà-phê đường, dầu ăn.',
    ],
    steps: [
      'Cho thịt bò với mỡ vào trộn đều, thêm hành tím băm, tỏi băm, hành lá và 1 gói Xốt Gia Vị Hoàn Chỉnh Barona - Thịt nướng sả ướp khoảng 15 phút.',
      'Sau khi thịt đã ngấm đều gia vị thì tiến hành cuộn thịt với lá lốt: Trải lá lốt lên mặt phẳng, quết thịt bò lên lá lốt vừa đủ, cho thanh sả lên rồi cuộn lại, cuộn vừa phải để cho thịt không bị rơi ra ngoài, sau đó cho lên bếp than nướng chín, lá lốt có màu nâu vàng đều là được.',
      'Xếp thịt bò cuộn lá lốt ra đĩa, trang trí thêm xà lách, rau thơm và cà rốt tỉa hoa.',
      'Khi ăn dùng với rau thơm các loại và cà-rốt, dưa leo đã ngâm chua.',
    ],
    duration: 20,
    complexity: Complexity.simple,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm8',
    name: 'Canh khổ qua chay',
    image: 'assets/images/meals/canh_kho_qua_chay.png',
    categories: [
      'c5',
    ],
    ingredients: [
      'Khổ qua: 2 trái',
      'Đậu hũ: 400g',
      'Cà rốt: 1 củ',
      'Nấm mèo 10g',
      'Hành bao rô: 1 nhánh',
      'Miến: 40g',
      'Tiêu: ½ muỗng',
      'Muối: ½ muỗng',
      '2 muỗng hạt nêm chay',
      '2 muỗng bột ngọt',
    ],
    steps: [
      'Phần nấm mèo bạn đem ngâm nước chừng 5 phút cho nấm mềm, rửa sạch với sau đó thái sợi nhỏ. Hành boa rô cắt gốc, rửa sạch rồi thái lát nhỏ, cà rốt thì bạn gọt bỏ vỏ, rửa sạch sau đó băm nhỏ như các nguyên liệu kể trên. Mỗi nguyên liệu sơ chế xong bạn để riêng ra một góc nhé.',
      'Đậu hũ trắng các bạn rửa sạch để cho ráo hết nước rồi nghiền thật nhuyễn, miến ngâm sơ với nước cho mềm rồi cắt ngắn khoảng 0,5 cm. Món chay sẽ không có thịt vì vậy chúng ta thay thế bằng đậu hũ và cà rốt nhưng cũng ngon không kém canh khổ qua thịt.',
      'Khổ qua bạn chọn quả vừa phải, xanh sau đó cắt thành khúc dài khoảng 1 ngón tay, nạo bỏ phần ruột bên trong sau đó đem rửa thật sạch với nước.',
      'Chúng ta tiến hành nấu canh khổ qua:',
      'Nhồi khổ qua: Dùng một chiếc tô lớn, cho các nguyên liệu đã chuẩn bị như cà rốt, nấm mèo, miến, hành boa rô, đậu hũ, ½ muỗng muối, 2 muỗng hạt nêm, ½ muỗng tiêu sau đó trộn đều cho thấm hết gia vị. Lần lượt chúng ta nhồi hỗn hợp vừa trộn vào từng miếng khổ qua vừa được cắt khúc cho đến khi hết.',
      'Bạn bắc nồi lên bếp, cho thêm chút dầu ăn vào và trút boa rô còn lại phi thơm, thêm 3 chén nước lọc đun sôi. Sau đó, cho lần lượt từng miếng khổ qua vừa nhồi vào nồi, thêm 1 muỗng hạt nêm chay.',
      'Đậy vung lại và đun trong khoảng 15 phút cho khổ qua chính mềm, nếm thêm gia vị cho vừa ăn rồi tắt bếp nhé. Để nấu món canh chay khổ qua ngon ngoài việc nêm nếm gia vị vừa thì bạn cần chú ý đến việc nhồi cho khổ qua không bị dính ra ngoài hay bị nứt khi cho vào nước lúc nấu, đồng thời giữ cho khổ qua không bị vàng.',
      'Bạn múc canh ra tô và thưởng thức cùng gia đình và bạn bè. Món canh chay khổ qua giúp bạn cân bằng giữa lượng chất béo và chất xơ. Canh khổ qua chay là món canh mát, món ăn hoàn toàn phù hợp với những chị em muốn ăn kiêng giảm cân. Các chị em hãy liệt vào danh sách ăn những món ăn kiêng của mình nhé. Món ăn có vị ngọt dị',
    ],
    duration: 40,
    complexity: Complexity.hard,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: 'm9',
    name: 'Vịt hầm bia',
    image: 'assets/images/meals/vit_ham_bia.png',
    categories: ['c6'],
    ingredients: [
      'Vịt: 1/2 con',
      'Bia: 1 lon',
      'Gia vị: Nước tương, muối ớt, đường',
      'Vỏ quế',
      'Gừng',
      'Hành',
      'Lá thơm',
      'Hoa hồi',
      'Chanh',
    ],
    steps: [
      'Thịt vịt nhặt sạch lông sau đó lấy chanh xoa đều rồi rửa sạch',
      'Cho thịt vịt vào một nồi nước sôi sau đó trụng sơ thịt vịt',
      'Lấy nồi áp suất cho thịt vịt vào sau đó đổ bia xấp mặt thịt, nếu không có nồi áp suất, bạn cho vào nồi hầm như bình thường.',
      'Cho 2 muỗng nước tương, 1 muỗng muối, 1 muỗng đường cùng tất cả các nguyên liệu đã chuẩn bị ở trên vào.',
      'Khuấy cho đều sau đó bạn đậy kín nắp lại, bắc nồi lên bếp',
      'Mới đầu để lửa to cho thịt nhanh chín, sau đó tầm 10 phút thì hạ lửa nhỏ liu riu từ 15 đến 20 phút cho đến khi nước sệt lại thì hãy tắt bếp.',
    ],
    duration: 35,
    complexity: Complexity.medium,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm10',
    name: 'Canh ngao chua',
    image: 'assets/images/meals/canh_ngao_chua.png',
    categories: [
      'c5',
    ],
    ingredients: [
      'Ngao 5 lạng',
      'Dứa 1 quả',
      'Cà chua 1 quả',
      'Sấu 2 quả (nếu có)',
      'Rau răm, hành lá, thì là, hành khô, gừng',
      'Nước mắm, bột canh, mì chính (hoặc hạt nêm).',
    ],
    steps: [
      'Dứa gọt vỏ, cắt mắt rồi thái miếng vừa ăn. Cà chua rửa sạch 1 quả bổ múi cau, 1 quả thái hạt lựu',
      'Hành lá, thì là, rau răm thái nhỏ. Hành khô băm nhỏ, gừng đập dập. Ngao rửa sạch rồi cho vào nồi luộc và thêm một chút muối trắng vào luộc cùng.',
      'Khi ngao mở miệng thì vớt chúng ra và tách lấy phần thịt, bỏ phần vỏ còn phần nước thì chắt ra bát to cho lắng cạn',
      'Ướt thịt ngao với chút nước mắm, mì chính, bột canh và một chút hành khô băm nhỏ.',
      'Làm nóng dầu ăn trong nồi rồi cho hành khô băm nhỏ vào phi thơm, sau đó cho phần cà chua thái hạt lựu vào xào, khi cà chua chín thì đổ ngao vào xào cùng khoảng 2, 3 phút thì múc ngao và cà chua ra bát.',
      'Đổ nước luộc ngao đã gạn bỏ cặn vào nồi vừa xào ngao, bỏ sấu, dứa, và gừng vào đun khoảng 10 phút, sau đó cho ngao và cà chua vào đun thêm 5 phút nữa. Nêm nếm gia vị cho vừa ăn, thêm hành lá, rau răm thì là vào rồi tăt bếp.',
      'Múc canh ra bát to và thưởng thức',
    ],
    duration: 35,
    complexity: Complexity.hard,
    affordability: Affordability.pricey,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: 'm11',
    name: 'Thịt gà om hạt dẻ',
    image: 'assets/images/meals/thit_ga_om_hat_de.png',
    categories: [
      'c2',
      'c3',
    ],
    ingredients: [
      'Gà: 1/2 con',
      'Hạt dẻ đã được bóc sạch vỏ: 14 hạt',
      'Gừng tươi: 10 gr',
      'Tỏi khô',
      'Hành lá',
      'Nước: 350 ml',
      'Những gia vị ướp gà: Dầu: 30 ml, bột bắp: 5 gr, hạt tiêu, đường',
      'Gia vị cho nước sốt: Bột bắp: 30 gr, nước: 40 ml',
      'Gia vị chế biến khác: Rượu nấu ăn: 15 ml, muối: 2,5 gr',
    ],
    steps: [
      'Thịt gà các bạn chặt thành những miếng vừa ăn, lưu ý có thể có kích thước ngang bằng với hạt dẻ đều được nhé. Sau đó các bạn cho vào ướp với gia vị trong khoảng 5 phút, trong thời gian này, chú ý dùng tay hoặc đũa trộn thật đều gà để được ngấm nhé. Hạt dẻ các bạn có thể mua loại chưa bóc vỏ hoặc đã bóc vỏ đều được, mình khuyên nên dùng loại đã bóc vỏ hơn vì tiết kiệm được khá nhiều thời gian và công sức cho việc chế biến món ăn đấyGừng tươi cạo sạch vỏ rồi rửa sạch, tỏi khô bóc sạch vỏ sau đó băm nhuyễn.',
      'Cho chảo lên bếp, sau đó cho thêm ít dầu, đợi chảo nóng thì cho thịt gà cùng với gừng và tỏi vào và đảo đều tay nhé',
      'Cứ tiếp tục đảo thật đều tay gà trên bếp cho đến khi chúng chuyển thành màu vàng nâu nhé, đến thời điểm này, bạn cho hạt dẻ cùng với rượu và nước đã chuẩn bị vào chảo nhé.',
      'Hòa bột bắp lẫn cùng với nước để sẵn sàng cho gia vị phần nước sốt nhé. Lúc này, thịt gà đã mềm, các bạn đổ bột bắp vừa hòa với nước vào đảo cho đều rồi đợi 1 chút cho nước sốt hơi sánh lại nhé. Sau đó các bạn cho hành lá đã rửa sạch cắt khúc vào nồi gà om hạt dẻ này rồi cho ra bát thưởng thức nhé.',
    ],
    duration: 45,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm12',
    name: 'Món sườn rim',
    image: 'assets/images/meals/mon_suon_rim.png',
    categories: [
      'c1',
      'c3',
    ],
    ingredients: [
      '2-3 dẻ sườn',
      '2 quả chanh',
      '20g gừng',
      '2 tép tỏi',
      '1 cây rau mùi',
      '4 muỗng canh mật ong',
      'xì dầu vừa đủ',
      '2 muỗng canh rượu nấu ăn',
      '1 ít vừng trắng rang (để trang trí)',
      '3g muối',
    ],
    steps: [
      'Tỏi băm nhỏ, gừng gọt vỏ băm nhỏ; chanh cắt đôi, 1 nửa cắt lát một nửa vắt lấy nước.',
      'Rau mùi rửa sạch, thái nhỏ.',
      'Trộn nước chanh với mật ong rồi để sang một bên.',
      'Đun sôi nồi nước, cho rượu, gừng, và sườn vào chần. Sau đó vớt sườn và gừng thái lát ra. Để ráo. Cách này giúp sườn sạch và hạn chế bớt bọt trong quá trình rim.',
      'Làm nóng chảo, thêm ít dầu ăn, sau đó cho gừng tỏi vào phi thơm. Thêm sườn vào rồi chiên cho hai mặt có màu nâu vàng.',
      'Thêm nước vừa đủ, xì dầu, chanh thái lát vào, đun sôi. Hạ nhỏ lửa, đun liu riu trong 40 phút cho sườn mềm.',
      'Thêm hỗn hợp mật ong, nước cốt chanh và muối vào, đảo đều một lát rồi tắt bếp.',
      'Cho sườn lên đĩa, rắc ít vừng trắng, rau mùi lên rồi thưởng thức.',
    ],
    duration: 40,
    complexity: Complexity.medium,
    affordability: Affordability.luxurious,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm13',
    name: 'Gà sốt tương ớt chua ngọt',
    image: 'assets/images/meals/ga_sot_tuong_ot_chua_ngot.png',
    categories: [
      'c3',
      'c4',
    ],
    ingredients: [
      '500gr thịt đùi gà có da',
      '50gr tinh bột bắp',
      '50gr bột chiên giòn',
      '1/2 muỗng cà phê muối tiêu',
      'Phần xốt: 2 muỗng canh tương ớt chua ngọt; 1 miếng nhỏ gừng thái sợi; 1 muỗng canh xì dầu; 1 muỗng canh dầu hào; 1 muỗng canh đường; 1 muỗng canh nước; 2 muỗng canh ớt + tỏi và hành băm nhỏ.',
    ],
    steps: [
      'Thịt rửa sạch, cắt miếng vừa ăn. Cho thịt vào âu cùng muối tiêu trộn đều, để 10 phút cho thấm.',
      'Sau đó cho thịt vào bao nilon cùng với hai loại bột xóc đều.',
      'Bắc dầu lên bếp (không cần quá nhiều dầu). Chờ dầu vừa nóng là cho thịt vào chiên với lửa vừa.',
      'Thịt chín có lớp da giòn là gắp ra đĩa.',
      'Bắc chảo khác lên bếp, cho vào 1 muỗng canh dầu, chờ dầu nóng cho ớt hành và tỏi băm vào xào thơm.',
      'Sau đó cho hết các gia vị cùng gừng và nước vào khuấy đều, nấu sôi. Khi nước xốt hơi sánh cho thịt gà chiên giòn vào đảo đều để xốt bám quanh các miếng thịt là tắt bếp.',
      'Thịt gà sốt tương ớt chua ngọt cho ra đĩa, rắc chút hành lá thái nhỏ. Món này ăn với cơm nóng rất ngon.',
    ],
    duration: 30,
    complexity: Complexity.simple,
    affordability: Affordability.luxurious,
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: false,
  ),
];
